### Dataset: Energy Efficiency with HL (heating load) as target

In [1]:
from ucimlrepo import fetch_ucirepo

energy_efficiency = fetch_ucirepo(id=242) 
  
X = energy_efficiency.data.features 
y = energy_efficiency.data.targets

var_df = energy_efficiency.variables
col_map = dict(zip(var_df["name"], var_df["description"]))
X = X.rename(columns=col_map)
y = y.rename(columns=col_map)

y = y[["Heating Load"]]
df = X.join(y)
df.head()

,Relative Compactness,Surface Area,Wall Area,Roof Area,Overall Height,Orientation,Glazing Area,Glazing Area Distribution,Heating Load
0,0.98,514.5,294.0,110.25,7.0,2,0.0,0,15.55
1,0.98,514.5,294.0,110.25,7.0,3,0.0,0,15.55
2,0.98,514.5,294.0,110.25,7.0,4,0.0,0,15.55
3,0.98,514.5,294.0,110.25,7.0,5,0.0,0,15.55
4,0.90,563.5,318.5,122.50,7.0,2,0.0,0,20.84

### Train test split

In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.1,     
    random_state=42,   
    shuffle=True
)

print(f"#X_train = {len(X_train)}   #y_train = {len(y_train)}")
print(f"#X_test = {len(X_test)}     #y_test = {len(y_test)}")

#X_train = 691   #y_train = 691
#X_test = 77     #y_test = 77

### EDF normalization

In [3]:
from src.edf import edf_normalize, col_denorm

X_train_norm, X_test_norm, _ = edf_normalize(X_train, X_test)
y_train_norm, y_test_norm, edf_models = edf_normalize(y_train, y_test)

y_denorm = col_denorm("Heating Load", edf_models)

### Basic evaluation for different features and target degrees

In [4]:
from src.features import moment_like_features, prepare_targets
from src.hcr import fit_lasso, plot_example_densities
from src.evaluation import mean_log_likelihood, mse_evaluation
from collections import defaultdict

N_vals = [n for n in range(2, 9)]
A = 3.
B=100.

ll_softplus_vals = defaultdict(dict)
ll_param_softplus_vals = defaultdict(dict)
ll_clip_vals = defaultdict(dict)

MSE_softplus_vals = defaultdict(dict)
MSE_param_softplus_vals = defaultdict(dict)
MSE_clip_vals = defaultdict(dict)

for n_feature in N_vals:
    for n_target in N_vals:
        print(f"----- Target deg. {n_target}, feature deg. {n_feature} -----")

        V_train = moment_like_features(X_train_norm, n_feature)
        V_test  = moment_like_features(X_test_norm, n_feature)

        targets_train = prepare_targets(y_train_norm, n_target)
        targets_test  = prepare_targets(y_test_norm, n_target)

        models = []
        for n in range(n_target):
            models.append(fit_lasso(V_train, targets_train[n]))

        plot_example_densities(V_test, y_test_norm, models,
                               name=f"Example densities (\"softplus\", features deg. {n_feature}, target deg. {n_target})",
                               method="softplus", seed=42, save=True)
        plot_example_densities(V_test, y_test_norm, models,
                               name=f"Example densities (\"param-softplus\", features deg. {n_feature}, target deg. {n_target})",
                               method="softplus", 
                               a=A, b=B, seed=42, save=True)
        plot_example_densities(V_test, y_test_norm, models,
                               name=f"Example densities (\"clip\", features deg. {n_feature}, target deg. {n_target})",
                               method="clip", seed=42, save=True)
        
        ll_softplus = mean_log_likelihood(V_test, y_test_norm, models)
        ll_param_softplus = mean_log_likelihood(V_test, y_test_norm, models,
                                                method="softplus", a=A, b=B)
        ll_clip = mean_log_likelihood(V_test, y_test_norm, models, method="clip")

        mse_softplus = mse_evaluation(V_test, y_test, models, y_denorm)
        mse_param_softplus = mse_evaluation(V_test, y_test, models, y_denorm,
                                            method="softplus", a=A, b=B)
        mse_clip = mse_evaluation(V_test, y_test, models, y_denorm, method="clip")
        
        ll_softplus_vals[n_target][n_feature] = ll_softplus
        ll_param_softplus_vals[n_target][n_feature] = ll_param_softplus
        ll_clip_vals[n_target][n_feature] = ll_clip

        MSE_softplus_vals[n_target][n_feature] = mse_softplus
        MSE_param_softplus_vals[n_target][n_feature] = mse_param_softplus
        MSE_clip_vals[n_target][n_feature] = mse_clip

----- Target deg. 2, feature deg. 2 -----
----- Target deg. 3, feature deg. 2 -----
----- Target deg. 4, feature deg. 2 -----
----- Target deg. 5, feature deg. 2 -----
----- Target deg. 6, feature deg. 2 -----
----- Target deg. 7, feature deg. 2 -----
----- Target deg. 8, feature deg. 2 -----
----- Target deg. 2, feature deg. 3 -----
----- Target deg. 3, feature deg. 3 -----
----- Target deg. 4, feature deg. 3 -----
----- Target deg. 5, feature deg. 3 -----
----- Target deg. 6, feature deg. 3 -----
----- Target deg. 7, feature deg. 3 -----
----- Target deg. 8, feature deg. 3 -----
----- Target deg. 2, feature deg. 4 -----
----- Target deg. 3, feature deg. 4 -----
----- Target deg. 4, feature deg. 4 -----
----- Target deg. 5, feature deg. 4 -----
----- Target deg. 6, feature deg. 4 -----
----- Target deg. 7, feature deg. 4 -----
----- Target deg. 8, feature deg. 4 -----
----- Target deg. 2, feature deg. 5 -----
----- Target deg. 3, feature deg. 5 -----
----- Target deg. 4, feature deg. 5 -----
----- Target deg. 5, feature deg. 5 -----
----- Target deg. 6, feature deg. 5 -----
----- Target deg. 7, feature deg. 5 -----
----- Target deg. 8, feature deg. 5 -----
----- Target deg. 2, feature deg. 6 -----
----- Target deg. 3, feature deg. 6 -----
----- Target deg. 4, feature deg. 6 -----
----- Target deg. 5, feature deg. 6 -----
----- Target deg. 6, feature deg. 6 -----
----- Target deg. 7, feature deg. 6 -----
----- Target deg. 8, feature deg. 6 -----
----- Target deg. 2, feature deg. 7 -----
----- Target deg. 3, feature deg. 7 -----
----- Target deg. 4, feature deg. 7 -----
----- Target deg. 5, feature deg. 7 -----
----- Target deg. 6, feature deg. 7 -----
----- Target deg. 7, feature deg. 7 -----
----- Target deg. 8, feature deg. 7 -----
----- Target deg. 2, feature deg. 8 -----
----- Target deg. 3, feature deg. 8 -----
----- Target deg. 4, feature deg. 8 -----
----- Target deg. 5, feature deg. 8 -----
----- Target deg. 6, feature deg. 8 -----
----- Target deg. 7, feature deg. 8 -----
----- Target deg. 8, feature deg. 8 -----

In [14]:
for n_feature in N_vals:
    for n_target in N_vals:
        print(f"Features deg. {n_feature}, Target deg. {n_target}:")

        print(f"  Mean log-likelihood (softplus):       {ll_softplus_vals[n_target][n_feature]:.4f}")
        print(f"  Mean log-likelihood (param-softplus): {ll_param_softplus_vals[n_target][n_feature]:.4f}")
        print(f"  Mean log-likelihood (clip):           {ll_clip_vals[n_target][n_feature]:.4f}")

        print(f"  MSE (softplus):                       {MSE_softplus_vals[n_target][n_feature]:.4f}")
        print(f"  MSE (param-softplus):                 {MSE_param_softplus_vals[n_target][n_feature]:.4f}")
        print(f"  MSE (clip):                           {MSE_clip_vals[n_target][n_feature]:.4f}")

Features deg. 2, Target deg. 2:
  Mean log-likelihood (softplus):       0.4933
  Mean log-likelihood (param-softplus): 0.8070
  Mean log-likelihood (clip):           0.6838
  MSE (softplus):                       28.4662
  MSE (param-softplus):                 11.6983
  MSE (clip):                           14.9911
Features deg. 2, Target deg. 3:
  Mean log-likelihood (softplus):       0.6033
  Mean log-likelihood (param-softplus): 0.9390
  Mean log-likelihood (clip):           0.8241
  MSE (softplus):                       27.7673
  MSE (param-softplus):                 8.9418
  MSE (clip):                           13.5442
Features deg. 2, Target deg. 4:
  Mean log-likelihood (softplus):       0.6548
  Mean log-likelihood (param-softplus): 0.9899
  Mean log-likelihood (clip):           0.8659
  MSE (softplus):                       28.2820
  MSE (param-softplus):                 9.0898
  MSE (clip):                           14.5121
Features deg. 2, Target deg. 5:
  Mean log-likelihood (softplus):       0.6885
  Mean log-likelihood (param-softplus): 1.0256
  Mean log-likelihood (clip):           0.9023
  MSE (softplus):                       28.2857
  MSE (param-softplus):                 9.0429
  MSE (clip):                           15.3539
Features deg. 2, Target deg. 6:
  Mean log-likelihood (softplus):       0.7064
  Mean log-likelihood (param-softplus): 1.0866
  Mean log-likelihood (clip):           0.9180
  MSE (softplus):                       28.8659
  MSE (param-softplus):                 8.3557
  MSE (clip):                           16.5763
Features deg. 2, Target deg. 7:
  Mean log-likelihood (softplus):       0.7311
  Mean log-likelihood (param-softplus): 1.1161
  Mean log-likelihood (clip):           0.9435
  MSE (softplus):                       28.3562
  MSE (param-softplus):                 7.9467
  MSE (clip):                           16.6652
Features deg. 2, Target deg. 8:
  Mean log-likelihood (softplus):       0.7317
  Mean log-likelihood (param-softplus): 1.1050
  Mean log-likelihood (clip):           0.9392
  MSE (softplus):                       28.3429
  MSE (param-softplus):                 8.0279
  MSE (clip):                           16.6744
Features deg. 3, Target deg. 2:
  Mean log-likelihood (softplus):       0.5381
  Mean log-likelihood (param-softplus): 0.9693
  Mean log-likelihood (clip):           0.7384
  MSE (softplus):                       25.2490
  MSE (param-softplus):                 5.5854
  MSE (clip):                           11.1084
Features deg. 3, Target deg. 3:
  Mean log-likelihood (softplus):       0.6531
  Mean log-likelihood (param-softplus): 1.0875
  Mean log-likelihood (clip):           0.8826
  MSE (softplus):                       24.5209
  MSE (param-softplus):                 5.2368
  MSE (clip):                           9.6608
Features deg. 3, Target deg. 4:
  Mean log-likelihood (softplus):       0.7079
  Mean log-likelihood (param-softplus): 1.1434
  Mean log-likelihood (clip):           0.9272
  MSE (softplus):                       24.9713
  MSE (param-softplus):                 6.4171
  MSE (clip):                           12.2932
Features deg. 3, Target deg. 5:
  Mean log-likelihood (softplus):       0.7397
  Mean log-likelihood (param-softplus): 1.1419
  Mean log-likelihood (clip):           0.9577
  MSE (softplus):                       24.8000
  MSE (param-softplus):                 4.5696
  MSE (clip):                           13.1904
Features deg. 3, Target deg. 6:
  Mean log-likelihood (softplus):       0.7744
  Mean log-likelihood (param-softplus): 1.2128
  Mean log-likelihood (clip):           0.9921
  MSE (softplus):                       25.6956
  MSE (param-softplus):                 4.6296
  MSE (clip):                           14.4642
Features deg. 3, Target deg. 7:
  Mean log-likelihood (softplus):       0.8235
  Mean log-likelihood (param-softplus): 1.2805
  Mean log-likelihood (clip):           1.0403
  MSE (softplus):                       25.6964
  MSE (param-softplus):                 4.2922
  MSE (clip):                           15.1319
Features deg. 3, Target deg. 8:
  Mean log-likelihood (softplus):       0.8284
  Mean log-likelihood (param-softplus): 1.2751
  Mean log-likelihood (clip):           1.0397
  MSE (softplus):                       25.9520
  MSE (param-softplus):                 4.4785
  MSE (clip):                           15.3310
Features deg. 4, Target deg. 2:
  Mean log-likelihood (softplus):       0.5755
  Mean log-likelihood (param-softplus): 0.9957
  Mean log-likelihood (clip):           0.7757
  MSE (softplus):                       24.4084
  MSE (param-softplus):                 5.4833
  MSE (clip):                           11.6826
Features deg. 4, Target deg. 3:
  Mean log-likelihood (softplus):       0.6977
  Mean log-likelihood (param-softplus): 1.1759
  Mean log-likelihood (clip):           0.9311
  MSE (softplus):                       23.3786
  MSE (param-softplus):                 5.3001
  MSE (clip):                           8.9472
Features deg. 4, Target deg. 4:
  Mean log-likelihood (softplus):       0.7688
  Mean log-likelihood (param-softplus): 1.2442
  Mean log-likelihood (clip):           1.0098
  MSE (softplus):                       23.1075
  MSE (param-softplus):                 4.7408
  MSE (clip):                           8.0609
Features deg. 4, Target deg. 5:
  Mean log-likelihood (softplus):       0.7972
  Mean log-likelihood (param-softplus): 1.2449
  Mean log-likelihood (clip):           1.0335
  MSE (softplus):                       23.2523
  MSE (param-softplus):                 5.5057
  MSE (clip):                           9.4735
Features deg. 4, Target deg. 6:
  Mean log-likelihood (softplus):       0.8356
  Mean log-likelihood (param-softplus): 1.2946
  Mean log-likelihood (clip):           1.0690
  MSE (softplus):                       23.5565
  MSE (param-softplus):                 3.5828
  MSE (clip):                           12.0642
Features deg. 4, Target deg. 7:
  Mean log-likelihood (softplus):       0.8853
  Mean log-likelihood (param-softplus): 1.3667
  Mean log-likelihood (clip):           1.1176
  MSE (softplus):                       23.4647
  MSE (param-softplus):                 3.3546
  MSE (clip):                           12.9865
Features deg. 4, Target deg. 8:
  Mean log-likelihood (softplus):       0.8881
  Mean log-likelihood (param-softplus): 1.3464
  Mean log-likelihood (clip):           1.1123
  MSE (softplus):                       23.6201
  MSE (param-softplus):                 3.2055
  MSE (clip):                           13.0143
Features deg. 5, Target deg. 2:
  Mean log-likelihood (softplus):       0.5811
  Mean log-likelihood (param-softplus): 0.9941
  Mean log-likelihood (clip):           0.7808
  MSE (softplus):                       24.8444
  MSE (param-softplus):                 6.2215
  MSE (clip):                           10.6008
Features deg. 5, Target deg. 3:
  Mean log-likelihood (softplus):       0.7043
  Mean log-likelihood (param-softplus): 1.1809
  Mean log-likelihood (clip):           0.9361
  MSE (softplus):                       22.9791
  MSE (param-softplus):                 5.1953
  MSE (clip):                           8.0789
Features deg. 5, Target deg. 4:
  Mean log-likelihood (softplus):       0.7787
  Mean log-likelihood (param-softplus): 1.2483
  Mean log-likelihood (clip):           1.0193
  MSE (softplus):                       23.0174
  MSE (param-softplus):                 4.8350
  MSE (clip):                           7.9451
Features deg. 5, Target deg. 5:
  Mean log-likelihood (softplus):       0.8107
  Mean log-likelihood (param-softplus): 1.2559
  Mean log-likelihood (clip):           1.0472
  MSE (softplus):                       22.7153
  MSE (param-softplus):                 5.5463
  MSE (clip):                           8.5443
Features deg. 5, Target deg. 6:
  Mean log-likelihood (softplus):       0.8496
  Mean log-likelihood (param-softplus): 1.2978
  Mean log-likelihood (clip):           1.0844
  MSE (softplus):                       23.4976
  MSE (param-softplus):                 3.6640
  MSE (clip):                           10.6607
Features deg. 5, Target deg. 7:
  Mean log-likelihood (softplus):       0.8993
  Mean log-likelihood (param-softplus): 1.3741
  Mean log-likelihood (clip):           1.1326
  MSE (softplus):                       23.3294
  MSE (param-softplus):                 3.2836
  MSE (clip):                           12.2150
Features deg. 5, Target deg. 8:
  Mean log-likelihood (softplus):       0.9022
  Mean log-likelihood (param-softplus): 1.3495
  Mean log-likelihood (clip):           1.1278
  MSE (softplus):                       23.4819
  MSE (param-softplus):                 3.3259
  MSE (clip):                           12.1245
Features deg. 6, Target deg. 2:
  Mean log-likelihood (softplus):       0.5822
  Mean log-likelihood (param-softplus): 0.9949
  Mean log-likelihood (clip):           0.7820
  MSE (softplus):                       24.8271
  MSE (param-softplus):                 6.2381
  MSE (clip):                           10.7177
Features deg. 6, Target deg. 3:
  Mean log-likelihood (softplus):       0.7057
  Mean log-likelihood (param-softplus): 1.1825
  Mean log-likelihood (clip):           0.9373
  MSE (softplus):                       22.9684
  MSE (param-softplus):                 5.2102
  MSE (clip):                           8.1102
Features deg. 6, Target deg. 4:
  Mean log-likelihood (softplus):       0.7810
  Mean log-likelihood (param-softplus): 1.2505
  Mean log-likelihood (clip):           1.0220
  MSE (softplus):                       22.9864
  MSE (param-softplus):                 4.8461
  MSE (clip):                           7.9255
Features deg. 6, Target deg. 5:
  Mean log-likelihood (softplus):       0.8128
  Mean log-likelihood (param-softplus): 1.2577
  Mean log-likelihood (clip):           1.0495
  MSE (softplus):                       22.6966
  MSE (param-softplus):                 5.5634
  MSE (clip):                           8.5533
Features deg. 6, Target deg. 6:
  Mean log-likelihood (softplus):       0.8516
  Mean log-likelihood (param-softplus): 1.2988
  Mean log-likelihood (clip):           1.0867
  MSE (softplus):                       23.4479
  MSE (param-softplus):                 3.6449
  MSE (clip):                           10.5952
Features deg. 6, Target deg. 7:
  Mean log-likelihood (softplus):       0.9014
  Mean log-likelihood (param-softplus): 1.3753
  Mean log-likelihood (clip):           1.1348
  MSE (softplus):                       23.2927
  MSE (param-softplus):                 3.2955
  MSE (clip):                           12.1579
Features deg. 6, Target deg. 8:
  Mean log-likelihood (softplus):       0.9042
  Mean log-likelihood (param-softplus): 1.3504
  Mean log-likelihood (clip):           1.1298
  MSE (softplus):                       23.4527
  MSE (param-softplus):                 3.3330
  MSE (clip):                           12.0095
Features deg. 7, Target deg. 2:
  Mean log-likelihood (softplus):       0.5840
  Mean log-likelihood (param-softplus): 0.9943
  Mean log-likelihood (clip):           0.7839
  MSE (softplus):                       24.7958
  MSE (param-softplus):                 6.5036
  MSE (clip):                           10.7684
Features deg. 7, Target deg. 3:
  Mean log-likelihood (softplus):       0.7090
  Mean log-likelihood (param-softplus): 1.1862
  Mean log-likelihood (clip):           0.9405
  MSE (softplus):                       22.9512
  MSE (param-softplus):                 5.1555
  MSE (clip):                           8.0240
Features deg. 7, Target deg. 4:
  Mean log-likelihood (softplus):       0.7865
  Mean log-likelihood (param-softplus): 1.2565
  Mean log-likelihood (clip):           1.0283
  MSE (softplus):                       23.1782
  MSE (param-softplus):                 4.9023
  MSE (clip):                           7.9599
Features deg. 7, Target deg. 5:
  Mean log-likelihood (softplus):       0.8195
  Mean log-likelihood (param-softplus): 1.2686
  Mean log-likelihood (clip):           1.0575
  MSE (softplus):                       22.7242
  MSE (param-softplus):                 5.6113
  MSE (clip):                           8.4994
Features deg. 7, Target deg. 6:
  Mean log-likelihood (softplus):       0.8582
  Mean log-likelihood (param-softplus): 1.3066
  Mean log-likelihood (clip):           1.0945
  MSE (softplus):                       23.5082
  MSE (param-softplus):                 3.8204
  MSE (clip):                           10.1909
Features deg. 7, Target deg. 7:
  Mean log-likelihood (softplus):       0.9076
  Mean log-likelihood (param-softplus): 1.3821
  Mean log-likelihood (clip):           1.1425
  MSE (softplus):                       23.3377
  MSE (param-softplus):                 3.4389
  MSE (clip):                           11.6265
Features deg. 7, Target deg. 8:
  Mean log-likelihood (softplus):       0.9103
  Mean log-likelihood (param-softplus): 1.3566
  Mean log-likelihood (clip):           1.1373
  MSE (softplus):                       23.4253
  MSE (param-softplus):                 3.3993
  MSE (clip):                           11.5398
Features deg. 8, Target deg. 2:
  Mean log-likelihood (softplus):       0.5847
  Mean log-likelihood (param-softplus): 0.9946
  Mean log-likelihood (clip):           0.7848
  MSE (softplus):                       24.7754
  MSE (param-softplus):                 6.5820
  MSE (clip):                           10.9457
Features deg. 8, Target deg. 3:
  Mean log-likelihood (softplus):       0.7098
  Mean log-likelihood (param-softplus): 1.1871
  Mean log-likelihood (clip):           0.9414
  MSE (softplus):                       22.9294
  MSE (param-softplus):                 5.1188
  MSE (clip):                           8.0152
Features deg. 8, Target deg. 4:
  Mean log-likelihood (softplus):       0.7883
  Mean log-likelihood (param-softplus): 1.2585
  Mean log-likelihood (clip):           1.0303
  MSE (softplus):                       23.2588
  MSE (param-softplus):                 4.8696
  MSE (clip):                           7.9269
Features deg. 8, Target deg. 5:
  Mean log-likelihood (softplus):       0.8210
  Mean log-likelihood (param-softplus): 1.2704
  Mean log-likelihood (clip):           1.0589
  MSE (softplus):                       22.7460
  MSE (param-softplus):                 5.6142
  MSE (clip):                           8.5387
Features deg. 8, Target deg. 6:
  Mean log-likelihood (softplus):       0.8600
  Mean log-likelihood (param-softplus): 1.3082
  Mean log-likelihood (clip):           1.0962
  MSE (softplus):                       23.5884
  MSE (param-softplus):                 3.8084
  MSE (clip):                           10.2429
Features deg. 8, Target deg. 7:
  Mean log-likelihood (softplus):       0.9093
  Mean log-likelihood (param-softplus): 1.3835
  Mean log-likelihood (clip):           1.1446
  MSE (softplus):                       23.4253
  MSE (param-softplus):                 3.4672
  MSE (clip):                           11.6409
Features deg. 8, Target deg. 8:
  Mean log-likelihood (softplus):       0.9119
  Mean log-likelihood (param-softplus): 1.3577
  Mean log-likelihood (clip):           1.1393
  MSE (softplus):                       23.4978
  MSE (param-softplus):                 3.4291
  MSE (clip):                           11.5578

In [6]:
def process_results(results_dict, reverse=True):
    sorted_items = sorted(
        ((n_target, n_features, val) for n_target, inner in results_dict.items() for n_features, val in inner.items()),
        key=lambda x: x[2],
        reverse=reverse
    )
    return sorted_items

In [7]:
def print_best_results(results_dict, results_type="", cal_method="", N_vals=10, reverse=True):
    sorted = process_results(results_dict, reverse=reverse)
    print(f"Best {results_type} values for \"{cal_method}\" calibration:")
    for id in range(N_vals):
        target_deg, feature_deg, val = sorted[id]
        print(f"{id+1}. Target deg: {target_deg}, feature deg: {feature_deg}")
        print(f"    {val:.4f}")

In [8]:
print_best_results(ll_softplus_vals, 
                   results_type="mean log-likelihood",
                   cal_method="softplus")

Best mean log-likelihood values for "softplus" calibration:
1. Target deg: 8, feature deg: 8
    0.9119
2. Target deg: 8, feature deg: 7
    0.9103
3. Target deg: 7, feature deg: 8
    0.9093
4. Target deg: 7, feature deg: 7
    0.9076
5. Target deg: 8, feature deg: 6
    0.9042
6. Target deg: 8, feature deg: 5
    0.9022
7. Target deg: 7, feature deg: 6
    0.9014
8. Target deg: 7, feature deg: 5
    0.8993
9. Target deg: 8, feature deg: 4
    0.8881
10. Target deg: 7, feature deg: 4
    0.8853

In [9]:
print_best_results(MSE_softplus_vals, 
                   results_type="mean squared error",
                   cal_method="softplus",
                   reverse=False)

Best mean squared error values for "softplus" calibration:
1. Target deg: 5, feature deg: 6
    22.6966
2. Target deg: 5, feature deg: 5
    22.7153
3. Target deg: 5, feature deg: 7
    22.7242
4. Target deg: 5, feature deg: 8
    22.7460
5. Target deg: 3, feature deg: 8
    22.9294
6. Target deg: 3, feature deg: 7
    22.9512
7. Target deg: 3, feature deg: 6
    22.9684
8. Target deg: 3, feature deg: 5
    22.9791
9. Target deg: 4, feature deg: 6
    22.9864
10. Target deg: 4, feature deg: 5
    23.0174

In [10]:
print_best_results(ll_param_softplus_vals, 
                   results_type="mean log-likelihood",
                   cal_method="param-softplus")

Best mean log-likelihood values for "param-softplus" calibration:
1. Target deg: 7, feature deg: 8
    1.3835
2. Target deg: 7, feature deg: 7
    1.3821
3. Target deg: 7, feature deg: 6
    1.3753
4. Target deg: 7, feature deg: 5
    1.3741
5. Target deg: 7, feature deg: 4
    1.3667
6. Target deg: 8, feature deg: 8
    1.3577
7. Target deg: 8, feature deg: 7
    1.3566
8. Target deg: 8, feature deg: 6
    1.3504
9. Target deg: 8, feature deg: 5
    1.3495
10. Target deg: 8, feature deg: 4
    1.3464

In [11]:
print_best_results(MSE_param_softplus_vals, 
                   results_type="mean squared error",
                   cal_method="param-softplus",
                   reverse=False)

Best mean squared error values for "param-softplus" calibration:
1. Target deg: 8, feature deg: 4
    3.2055
2. Target deg: 7, feature deg: 5
    3.2836
3. Target deg: 7, feature deg: 6
    3.2955
4. Target deg: 8, feature deg: 5
    3.3259
5. Target deg: 8, feature deg: 6
    3.3330
6. Target deg: 7, feature deg: 4
    3.3546
7. Target deg: 8, feature deg: 7
    3.3993
8. Target deg: 8, feature deg: 8
    3.4291
9. Target deg: 7, feature deg: 7
    3.4389
10. Target deg: 7, feature deg: 8
    3.4672

In [12]:
print_best_results(ll_clip_vals, 
                   results_type="mean log-likelihood",
                   cal_method="clip")

Best mean log-likelihood values for "clip" calibration:
1. Target deg: 7, feature deg: 8
    1.1446
2. Target deg: 7, feature deg: 7
    1.1425
3. Target deg: 8, feature deg: 8
    1.1393
4. Target deg: 8, feature deg: 7
    1.1373
5. Target deg: 7, feature deg: 6
    1.1348
6. Target deg: 7, feature deg: 5
    1.1326
7. Target deg: 8, feature deg: 6
    1.1298
8. Target deg: 8, feature deg: 5
    1.1278
9. Target deg: 7, feature deg: 4
    1.1176
10. Target deg: 8, feature deg: 4
    1.1123

In [13]:
print_best_results(MSE_clip_vals, 
                   results_type="mean squared error",
                   cal_method="clip",
                   reverse=False)

Best mean squared error values for "clip" calibration:
1. Target deg: 4, feature deg: 6
    7.9255
2. Target deg: 4, feature deg: 8
    7.9269
3. Target deg: 4, feature deg: 5
    7.9451
4. Target deg: 4, feature deg: 7
    7.9599
5. Target deg: 3, feature deg: 8
    8.0152
6. Target deg: 3, feature deg: 7
    8.0240
7. Target deg: 4, feature deg: 4
    8.0609
8. Target deg: 3, feature deg: 5
    8.0789
9. Target deg: 3, feature deg: 6
    8.1102
10. Target deg: 5, feature deg: 7
    8.4994

### CV for top basic results

In [19]:
from src.cv import cross_validate, print_cv_results

def cv_top(X, y, results_dict, 
           results_type, method,
           a=1, b=1, eps=1e-6,
           N_vals=5, reverse=True):
    sorted = process_results(results_dict, reverse=reverse)
    results = []
    print(f"CV for top {results_type} values with \"{method}\" calibration:")
    if method=="param-softplus": method="softplus"

    for id in range(N_vals):
        target_deg, feature_deg, _ = sorted[id]
        print(f"{id+1}. Target deg: {target_deg}, feature deg: {feature_deg}")
        ll_results, mse_results = cross_validate(X, y,
                                                 feature_deg, target_deg,
                                                 method=method,
                                                 a=a, b=b, eps=eps)
        results.append({"target_deg": target_deg,
                        "feature_deg": feature_deg,
                        "ll_results": ll_results,
                        "mse_results": mse_results})
        print_cv_results(ll_results, mse_results)
    return results

In [20]:
cv_ll_softplus_results = cv_top(X, y, ll_softplus_vals,
                                results_type="mean log-likelihood",
                                method="softplus")

CV for top mean log-likelihood values with "softplus" calibration:
1. Target deg: 8, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.84 0.88 0.92 0.81 0.9  0.92 0.85 0.83 0.83 0.81]
  mean LL : 0.8596
  std LL  : 0.0406

Mean square error:
  per fold: [18.17 18.44 17.22 22.4  27.88 16.02 16.96 24.36 18.08 17.25]
  mean MSE: 19.6778
  std MSE : 3.6824
2. Target deg: 8, feature deg: 7
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.84 0.88 0.92 0.81 0.9  0.91 0.85 0.83 0.83 0.81]
  mean LL : 0.8589
  std LL  : 0.0402

Mean square error:
  per fold: [18.2  18.35 17.23 22.28 27.78 16.04 16.89 24.37 18.13 17.29]
  mean MSE: 19.6543
  std MSE : 3.6527
3. Target deg: 7, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.83 0.89 0.93 0.82 0.89 0.91 0.81 0.82 0.82 0.8 ]
  mean LL : 0.8519
  std LL  : 0.0435

Mean square error:
  per fold: [17.98 18.16 17.13 22.47 28.   15.85 17.03 24.34 17.84 17.04]
  mean MSE: 19.5830
  std MSE : 3.7733
4. Target deg: 7, feature deg: 7
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.83 0.88 0.93 0.82 0.89 0.91 0.81 0.82 0.82 0.8 ]
  mean LL : 0.8512
  std LL  : 0.0431

Mean square error:
  per fold: [18.   18.06 17.14 22.4  27.93 15.88 16.98 24.37 17.86 17.04]
  mean MSE: 19.5654
  std MSE : 3.7593
5. Target deg: 8, feature deg: 6
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.84 0.88 0.92 0.81 0.9  0.91 0.85 0.83 0.83 0.8 ]
  mean LL : 0.8559
  std LL  : 0.0401

Mean square error:
  per fold: [18.24 18.34 17.2  22.16 27.76 16.14 16.87 24.33 18.01 17.46]
  mean MSE: 19.6513
  std MSE : 3.6230

In [21]:
cv_mse_softplus_results = cv_top(X, y, MSE_softplus_vals,
                                 results_type="mean squared error",
                                 method="softplus",
                                 reverse=False)

CV for top mean squared error values with "softplus" calibration:
1. Target deg: 5, feature deg: 6
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.77 0.78 0.81 0.77 0.84 0.82 0.73 0.76 0.74 0.71]
  mean LL : 0.7719
  std LL  : 0.0391

Mean square error:
  per fold: [17.91 17.76 17.14 21.69 27.11 15.78 16.69 24.08 17.97 17.31]
  mean MSE: 19.3441
  std MSE : 3.5140
2. Target deg: 5, feature deg: 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.77 0.77 0.81 0.77 0.84 0.82 0.73 0.76 0.74 0.71]
  mean LL : 0.7712
  std LL  : 0.0390

Mean square error:
  per fold: [17.91 17.77 17.14 21.66 27.14 15.78 16.68 24.07 17.96 17.31]
  mean MSE: 19.3434
  std MSE : 3.5181
3. Target deg: 5, feature deg: 7
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.77 0.78 0.81 0.77 0.84 0.82 0.73 0.76 0.74 0.72]
  mean LL : 0.7748
  std LL  : 0.0392

Mean square error:
  per fold: [17.86 17.75 17.04 21.71 27.29 15.55 16.57 23.99 17.98 17.22]
  mean MSE: 19.2958
  std MSE : 3.5886
4. Target deg: 5, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.78 0.78 0.82 0.77 0.84 0.82 0.73 0.76 0.74 0.72]
  mean LL : 0.7754
  std LL  : 0.0394

Mean square error:
  per fold: [17.84 17.73 16.95 21.69 27.33 15.48 16.57 23.96 17.95 17.2 ]
  mean MSE: 19.2695
  std MSE : 3.6110
5. Target deg: 3, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.64 0.64 0.67 0.66 0.71 0.68 0.55 0.64 0.62 0.59]
  mean LL : 0.6399
  std LL  : 0.0438

Mean square error:
  per fold: [18.07 17.13 17.06 21.91 27.32 14.76 15.97 23.81 18.07 17.15]
  mean MSE: 19.1264
  std MSE : 3.7434

In [23]:
cv_ll_param_softplus_results = cv_top(X, y, ll_param_softplus_vals,
                                      results_type="mean log-likelihood",
                                      method="param-softplus",
                                      a=3., b=100.)

CV for top mean log-likelihood values with "param-softplus" calibration:
1. Target deg: 7, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.13 1.29 1.48 1.1  1.25 1.34 1.05 1.2  1.07 1.17]
  mean LL : 1.2094
  std LL  : 0.1261

Mean square error:
  per fold: [3.59 2.78 2.15 3.41 5.46 3.   4.58 4.09 5.17 2.45]
  mean MSE: 3.6669
  std MSE : 1.0763
2. Target deg: 7, feature deg: 7
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.13 1.29 1.48 1.1  1.26 1.34 1.06 1.2  1.08 1.17]
  mean LL : 1.2098
  std LL  : 0.1252

Mean square error:
  per fold: [3.55 2.71 2.15 3.3  5.45 3.01 4.56 4.1  5.12 2.46]
  mean MSE: 3.6410
  std MSE : 1.0719
3. Target deg: 7, feature deg: 6
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.12 1.29 1.48 1.11 1.26 1.33 1.06 1.2  1.08 1.17]
  mean LL : 1.2090
  std LL  : 0.1258

Mean square error:
  per fold: [3.5  2.71 2.12 3.22 5.42 2.99 4.57 4.05 5.07 2.53]
  mean MSE: 3.6178
  std MSE : 1.0609
4. Target deg: 7, feature deg: 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.12 1.29 1.48 1.11 1.26 1.33 1.06 1.2  1.08 1.17]
  mean LL : 1.2083
  std LL  : 0.1254

Mean square error:
  per fold: [3.46 2.7  2.1  3.19 5.36 3.01 4.54 4.03 5.03 2.54]
  mean MSE: 3.5955
  std MSE : 1.0464
5. Target deg: 7, feature deg: 4
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.09 1.28 1.47 1.11 1.26 1.31 1.05 1.2  1.08 1.15]
  mean LL : 1.1997
  std LL  : 0.1245

Mean square error:
  per fold: [3.34 2.77 2.27 3.09 5.23 3.33 4.5  4.12 4.95 2.77]
  mean MSE: 3.6367
  std MSE : 0.9534

In [24]:
cv_mse_param_softplus_results = cv_top(X, y, MSE_param_softplus_vals,
                                       results_type="mean squared error",
                                       method="param-softplus",
                                       a=3., b=100.,
                                       reverse=False)

CV for top mean squared error values with "param-softplus" calibration:
1. Target deg: 8, feature deg: 4
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.12 1.26 1.45 1.07 1.29 1.3  1.16 1.2  1.1  1.14]
  mean LL : 1.2074
  std LL  : 0.1107

Mean square error:
  per fold: [3.32 2.92 2.4  2.91 5.18 3.63 4.5  4.06 4.78 2.79]
  mean MSE: 3.6478
  std MSE : 0.8925
2. Target deg: 7, feature deg: 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.12 1.29 1.48 1.11 1.26 1.33 1.06 1.2  1.08 1.17]
  mean LL : 1.2083
  std LL  : 0.1254

Mean square error:
  per fold: [3.46 2.7  2.1  3.19 5.36 3.01 4.54 4.03 5.03 2.54]
  mean MSE: 3.5955
  std MSE : 1.0464
3. Target deg: 7, feature deg: 6
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.12 1.29 1.48 1.11 1.26 1.33 1.06 1.2  1.08 1.17]
  mean LL : 1.2090
  std LL  : 0.1258

Mean square error:
  per fold: [3.5  2.71 2.12 3.22 5.42 2.99 4.57 4.05 5.07 2.53]
  mean MSE: 3.6178
  std MSE : 1.0609
4. Target deg: 8, feature deg: 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.14 1.27 1.45 1.07 1.28 1.33 1.16 1.19 1.09 1.15]
  mean LL : 1.2142
  std LL  : 0.1130

Mean square error:
  per fold: [3.34 2.76 2.21 3.14 5.3  3.32 4.42 4.   4.92 2.66]
  mean MSE: 3.6066
  std MSE : 0.9670
5. Target deg: 8, feature deg: 6
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.15 1.27 1.45 1.06 1.28 1.34 1.16 1.19 1.09 1.15]
  mean LL : 1.2145
  std LL  : 0.1138

Mean square error:
  per fold: [3.37 2.78 2.2  3.19 5.34 3.35 4.43 4.01 4.97 2.65]
  mean MSE: 3.6265
  std MSE : 0.9781

In [25]:
cv_ll_clip_results = cv_top(X, y, ll_clip_vals,
                            results_type="mean log-likelihood",
                            method="clip")

CV for top mean log-likelihood values with "clip" calibration:
1. Target deg: 7, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.04 1.07 1.17 1.02 0.96 1.14 1.01 1.04 1.03 0.87]
  mean LL : 1.0346
  std LL  : 0.0799

Mean square error:
  per fold: [ 9.12  8.53  7.82 10.79 15.48  7.75  7.98 12.68  8.91  8.19]
  mean MSE: 9.7258
  std MSE : 2.4161
2. Target deg: 7, feature deg: 7
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.04 1.07 1.17 1.02 0.96 1.13 1.01 1.04 1.03 0.87]
  mean LL : 1.0338
  std LL  : 0.0795

Mean square error:
  per fold: [ 9.09  8.55  7.86 10.76 15.46  7.78  7.98 12.7   8.94  8.17]
  mean MSE: 9.7298
  std MSE : 2.4065
3. Target deg: 8, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.06 0.95 1.16 0.86 0.97 1.14 1.06 1.03 1.03 0.88]
  mean LL : 1.0134
  std LL  : 0.0951

Mean square error:
  per fold: [ 9.28  8.67  7.77 10.67 15.42  7.93  7.71 12.5   8.92  8.45]
  mean MSE: 9.7318
  std MSE : 2.3586
4. Target deg: 8, feature deg: 7
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.05 0.95 1.16 0.86 0.97 1.14 1.06 1.03 1.03 0.88]
  mean LL : 1.0125
  std LL  : 0.0946

Mean square error:
  per fold: [ 9.24  8.67  7.8  10.68 15.4   7.97  7.65 12.51  8.88  8.41]
  mean MSE: 9.7196
  std MSE : 2.3609
5. Target deg: 7, feature deg: 6
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [1.04 1.08 1.16 1.02 0.96 1.13 1.01 1.04 1.03 0.86]
  mean LL : 1.0318
  std LL  : 0.0798

Mean square error:
  per fold: [ 9.06  8.48  7.86 10.87 15.43  7.88  7.87 12.79  8.79  8.47]
  mean MSE: 9.7499
  std MSE : 2.4077

In [26]:
cv_mse_clip_results = cv_top(X, y, MSE_clip_vals,
                             results_type="mean squared error",
                             method="clip",
                             reverse=False)

CV for top mean squared error values with "clip" calibration:
1. Target deg: 4, feature deg: 6
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.95 0.89 0.99 0.92 0.84 1.   0.88 0.93 0.93 0.72]
  mean LL : 0.9051
  std LL  : 0.0770

Mean square error:
  per fold: [ 7.17  5.52  5.99  7.27 10.84  6.36  5.32  7.59  7.11  5.24]
  mean MSE: 6.8396
  std MSE : 1.5654
2. Target deg: 4, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.95 0.77 0.99 0.91 0.84 1.01 0.89 0.93 0.93 0.72]
  mean LL : 0.8946
  std LL  : 0.0880

Mean square error:
  per fold: [ 6.9   5.46  5.84  7.28 10.97  6.28  5.13  7.64  7.07  5.02]
  mean MSE: 6.7593
  std MSE : 1.6520
3. Target deg: 4, feature deg: 5
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.94 0.89 0.99 0.93 0.84 1.   0.88 0.93 0.93 0.72]
  mean LL : 0.9049
  std LL  : 0.0769

Mean square error:
  per fold: [ 7.01  5.51  5.99  7.24 10.71  6.37  5.28  7.5   7.12  5.22]
  mean MSE: 6.7947
  std MSE : 1.5322
4. Target deg: 4, feature deg: 7
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.95 0.86 0.99 0.91 0.84 1.   0.89 0.93 0.93 0.72]
  mean LL : 0.9036
  std LL  : 0.0779

Mean square error:
  per fold: [ 6.91  5.47  5.92  7.25 10.93  6.31  5.18  7.66  7.08  5.04]
  mean MSE: 6.7766
  std MSE : 1.6306
5. Target deg: 3, feature deg: 8
Fold 1
Fold 2
Fold 3
Fold 4
Fold 5
Fold 6
Fold 7
Fold 8
Fold 9
Fold 10

Log-likelihood:
  per fold: [0.85 0.81 0.89 0.71 0.93 0.9  0.24 0.85 0.64 0.8 ]
  mean LL : 0.7610
  std LL  : 0.1936

Mean square error:
  per fold: [ 6.15  6.25  5.77  7.97 11.42  6.14  5.09  9.65  6.54  5.81]
  mean MSE: 7.0787
  std MSE : 1.9032

### Results summary

In [27]:
import pandas as pd
import numpy as np

def results_to_df(results):
    rows = []
    for r in results:
        rows.append({
            "target_deg": r["target_deg"],
            "feature_deg": r["feature_deg"],
            "ll_mean": np.mean(r["ll_results"]),
            "ll_std": np.std(r["ll_results"]),
            "mse_mean": np.mean(r["mse_results"]),
            "mse_std": np.std(r["mse_results"]),
        })
    return pd.DataFrame(rows)

In [28]:
results = {
    "ll_softplus": cv_ll_softplus_results,
    "mse_softplus": cv_mse_softplus_results,

    "ll_param_softplus": cv_ll_param_softplus_results,
    "mse_param_softplus": cv_mse_param_softplus_results,

    "ll_clip": cv_ll_clip_results,
    "mse_clip": cv_mse_clip_results,
}

In [29]:
results_dfs = {key : results_to_df(val) for key, val in results.items()}

In [30]:
df = results_dfs["ll_softplus"]
df

   target_deg  feature_deg   ll_mean    ll_std   mse_mean   mse_std
0           8            8  0.859608  0.040608  19.677821  3.682443
1           8            7  0.858929  0.040220  19.654283  3.652677
2           7            8  0.851872  0.043531  19.582961  3.773343
3           7            7  0.851191  0.043141  19.565382  3.759285
4           8            6  0.855889  0.040073  19.651283  3.623018

In [31]:
df = results_dfs["mse_softplus"]
df

   target_deg  feature_deg   ll_mean    ll_std   mse_mean   mse_std
0           5            6  0.771922  0.039127  19.344125  3.514035
1           5            5  0.771206  0.039048  19.343393  3.518071
2           5            7  0.774832  0.039226  19.295822  3.588557
3           5            8  0.775392  0.039431  19.269474  3.611001
4           3            8  0.639899  0.043827  19.126406  3.743433

In [32]:
df = results_dfs["ll_param_softplus"]
df

   target_deg  feature_deg   ll_mean    ll_std  mse_mean   mse_std
0           7            8  1.209406  0.126062  3.666906  1.076268
1           7            7  1.209785  0.125244  3.640976  1.071912
2           7            6  1.208972  0.125765  3.617753  1.060907
3           7            5  1.208302  0.125436  3.595493  1.046377
4           7            4  1.199650  0.124548  3.636729  0.953397

In [33]:
df = results_dfs["mse_param_softplus"]
df

   target_deg  feature_deg   ll_mean    ll_std  mse_mean   mse_std
0           8            4  1.207419  0.110687  3.647847  0.892528
1           7            5  1.208302  0.125436  3.595493  1.046377
2           7            6  1.208972  0.125765  3.617753  1.060907
3           8            5  1.214203  0.113045  3.606554  0.966998
4           8            6  1.214510  0.113796  3.626501  0.978138

In [34]:
df = results_dfs["ll_clip"]
df

   target_deg  feature_deg   ll_mean    ll_std  mse_mean   mse_std
0           7            8  1.034576  0.079938  9.725834  2.416137
1           7            7  1.033846  0.079524  9.729765  2.406462
2           8            8  1.013393  0.095148  9.731790  2.358616
3           8            7  1.012542  0.094647  9.719591  2.360885
4           7            6  1.031765  0.079825  9.749875  2.407678

In [35]:
df = results_dfs["mse_clip"]
df

   target_deg  feature_deg   ll_mean    ll_std  mse_mean   mse_std
0           4            6  0.905113  0.077009  6.839573  1.565369
1           4            8  0.894567  0.087980  6.759264  1.651998
2           4            5  0.904947  0.076927  6.794660  1.532180
3           4            7  0.903554  0.077943  6.776647  1.630622
4           3            8  0.760975  0.193556  7.078725  1.903237